### ISSUE TITLE
I always get an error

### ISSUE THREAD

**Issue by ismat-d** [jpes707/itunes-dl#1]
Warning! Song will not be downloaded because URL could not be found after ten tries

**Comment by jpes707** [comment]
Thank you for bringing up this issue. The program has been updated and the errors should be resolved now.

**Comment by ismat-d** [comment]
![image](https://user-images.githubusercontent.com/34811824/132987988-fa36f6d4-2c01-4abd-bd31-fc9656e65e45.jpeg)

**Comment by ismat-d** [comment]
Still not working , sorry 🤷‍♂️
